#! /bin/bash
export ASSISTENTE="
<window title=\"Assistente de conexão\" icon-name=\"connect_established\" window_position=\"1\">
<vbox>
<hbox>
<vbox homogeneous=\"true\">
<text label=\"Usuário:\"></text>
<text label=\"Senha:\"></text>
<text label=\"IP/Porta:\"></text>
</vbox>
<vbox>
<entry><variable>USERIN</variable></entry>
<entry visibility=\"false\" caps-lock-warning=\"true\"><variable>PASSIN</variable></entry>
<entry><variable>IPIN</variable></entry>

</vbox>
</hbox>
<vbox>
<button label=\"CONECTAR\"><action>rdesktop -u $"USERIN" -p $"PASSIN" -k pt-br -a 16ppp $"IPIN"</action><action type=\"exit\">Exit</action></button>
</vbox>
</vbox>
</window>
"
gtkdialog --program=ASSISTENTE
